---

- name: define hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: ensure vars are defined
      fail:
        msg: "{{ item }} must be defined!"
      when: lookup('vars', item) is undefined
      loop:
        - emqx_cluster_name
        - emqx_emqx_num
        - emqx_loadgen_num
    - name: create groups and hosts (emqx)
      add_host:
        name: "emqx-{{ item }}.int.{{ emqx_cluster_name }}"
        group: emqx
        ansible_user: ubuntu
      loop: "{{ range(0, emqx_emqx_num | int) | list }}"
    - name: create groups and hosts (loadgen)
      add_host:
        name: "loadgen-{{ item }}.int.{{ emqx_cluster_name }}"
        group: loadgen
        ansible_user: ubuntu
      loop: "{{ range(0, emqx_loadgen_num | int) | list }}"
    # - name: set db backend configs
    #   block:
    #     - name: define cores and replicants
    #       debug:
    #         msg: "{{ cores }}"
    #     - name: define cores and replicants
    #       debug:
    #         msg: "{{ replicants }}"
    #   when: emqx_db_backend is defined and emqx_num_cores is defined
    #   vars:
    #     cores: "{{ groups['emqx'][0:(emqx_num_cores | int)] }}"
    #     replicants: "{{ groups['emqx'][(emqx_num_cores | int):] }}"

- name: config emqx
  hosts: emqx
  become: yes
  become_user: root
  tasks:
    - name: apply tuning to emqx | set kernel parameters
      script: ./files/tuning-emqx.sh
    - name: set db backend configs
      block:
        - name: set facts
          set_fact:
            emqx_db_role: "{{ 'core' if inventory_hostname in cores else 'replicant' }}"
        - debug:
            var: "{{ item }}"
          loop:
            - cores
            - replicants
        - name: ensure etc directory
          file:
            path: /etc/emqx
            state: directory
        - name: set cluster-override.conf
          template:
            src: cluster-override.conf
            dest: /etc/emqx/cluster-override.conf
        - name: stop emqx
          systemd:
            name: emqx
            state: stopped
        - name: drop mnesia data and the logs
          shell: "rm -rf {{ item }}/*"
          with_items:
            - "/var/lib/emqx/mnesia"
            - "/var/log/emqx"
        - name: restart emqx
          systemd:
            name: emqx
            state: started
      when: emqx_db_backend is defined and emqx_num_cores is defined
      vars:
        cores: "{{ groups['emqx'][0:(emqx_num_cores | int)] }}"
        replicants: "{{ groups['emqx'][(emqx_num_cores | int):] }}"

- name: apply tuning to loadgen
  hosts: loadgen
  become: yes
  become_user: root
  tasks:
    - name: set kernel parameters
      script: ./files/tuning-loadgen.sh

...
